platform :ios, '15.0'

target 'aft-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aft-ios
  pod 'KeychainSwift', '~> 20.0'
  pod 'Alamofire', '~> 5.5'
end
