version: 0.2

env:
  exported-variables:
    - IMAGE_ID

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - cd api
      - curl "https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip" -o packer.zip
      - unzip packer.zip -d packer
      - mv packer /usr/local/
      - export PATH="$PATH:/usr/local/packer"
      - npm ci
      - npm t
      - packer build packer.pkr.hcl
      - IMAGE_ID=$(aws ec2 describe-images --filters "Name=owner-id,Values=008356366354" --filters "Name=name,Values=aft-api" --region eu-west-1 | jq -r .Images[0].ImageId)
