version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd web
      - npm ci
      - npm t
      - npm run build:prod
      - aws s3 sync build s3://$BUCKET --cache-control max-age=$CACHE_MAX_AGE --delete
artifacts:
  files:
    - "**/*"
